name: ohnost
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0-406.0.dev <3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dart_json_mapper: ^2.2.7+3
  dynamic_color: ^1.5.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_markdown: ^0.6.13
  flutter_widget_from_html: ^0.9.0+2
  google_fonts: ^3.0.1
  heroicons_flutter: ^0.2.3
  modal_bottom_sheet:
    git:
      url: https://github.com/CoolDude53/modal_bottom_sheet.git
      ref: d3779be7d661481cc0d99090d6356a286ae4f86b
      path: modal_bottom_sheet
  path_provider: ^2.0.11
  phosphor_flutter: ^1.4.0
  reflectable: ^4.0.4
  routemaster: ^1.0.1
  shared_preferences: ^2.0.15
  tuple: ^2.0.1
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
